# Generated by Django 3.2 on 2021-05-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Задание')),
                ('text', models.TextField(blank=True, verbose_name='Описание задания')),
                ('in_date', models.DateTimeField(verbose_name='Дата начала')),
                ('out_date', models.DateTimeField(blank=True, verbose_name='Дата окончания')),
                ('file_data', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
