# Generated by Django 3.2 on 2021-05-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file_data',
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.task')),
            ],
        ),
    ]
