# Generated by Django 3.2 on 2021-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20210502_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
